				<section class="page-top">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<ul class="breadcrumb">
									<li><a href="/">Home</a></li>
									<li class="active">Cases e Temas</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h1>Cases e Temas</h1>
							</div>
						</div>
					</div>
				</section>

				<div class="sort-source-wrapper">
					<div class="container">
						<ul class="nav nav-pills sort-source secundary pull-right" data-sort-id="portfolio" data-option-key="filter">
							<li data-option-value="*" class="active"><a href="#">Todos</a></li>
							<li data-option-value=".cases"><a href="#">Cases</a></li>
							<li data-option-value=".temas"><a href="#">Temas</a></li>
						</ul>
					</div>
				</div>

				<ul class="portfolio-list sort-destination full-width" data-sort-id="portfolio">
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://themes.semicolonweb.com/html/canvas/index.php" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Canvas" class="img-responsive" src="/img/canvas.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Canvas</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Canvas" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					
					
					
                    <li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://www.ansonika.com/citytours/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="City Tours" class="img-responsive" src="/img/cityTours.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">City Tours</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="City Tours" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://themes.ht2.pl/euforia/index.html" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Euforia" class="img-responsive" src="/img/euforia.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Euforia</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Euforia" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://nunforest.com/housebuild/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="House Build" class="img-responsive" src="/img/housebuild.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">House Build</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="House Build" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li> 
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://nunforest.com/site/imago-demo/multipurpose/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Imago" class="img-responsive" src="/img/imago.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Imago</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Imago" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li> 

					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://cdn.mosaicpro.biz/themekit-3.6.3-final/dist/themes/music/index.html" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Music" class="img-responsive" src="/img/music.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Music</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Music" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://showcase.thememountain.com/?theme=nietzsche" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Nietzsche" class="img-responsive" src="/img/nietzche.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Nietzsche</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Nietzsche" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://pivot.mediumra.re/index.html" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Pivot" class="img-responsive" src="/img/pivot.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Pivot</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Pivot" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>                 
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://jellythemes.com/themes/elixir/02/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Restaurant" class="img-responsive" src="/img/restaurant.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Restaurant</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Restaurant" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>                 
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://rhythm.bestlooker.pro/intro.html" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Rhythm" class="img-responsive" src="/img/rhythm.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Rhythm</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Rhythm" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://www.gt3themes.com/website-templates/soho/fullscreen_slider.html" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Soho" class="img-responsive" src="/img/soho.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Soho</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Soho" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>                 
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://solidus.orange-themes.com/html/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Solidus" class="img-responsive" src="/img/solidus.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Solidus</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Solidus" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>                 
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://demo.samuli.me/smartstart/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Smart Start" class="img-responsive" src="/img/smartstart.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Smart Start</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Smart Start" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://themes.mediacreed.com/html/synergy/#portfolio.html" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Synergy" class="img-responsive" src="/img/synergy.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Synergy</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Synergy" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>  
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://vasterad.com/themes/nevia/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Nevia" class="img-responsive" src="/img/nevia.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Nevia</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Nevia" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://template.progressive.itembridge.com/2.2.6/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Progressive" class="img-responsive" src="/img/progressive.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Progressive</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Progressive" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://demo.rocknrolladesigns.com/html/jarvis/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Jarvis" class="img-responsive" src="/img/jarvis.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Jarvis</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Jarvis" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>  
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://rbista.com/demos/zwin/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Zwin" class="img-responsive" src="/img/zwin.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Zwin</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Zwin" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>	
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://vasterad.com/themes/centum/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Centum" class="img-responsive" src="/img/centum.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Centum</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Centum" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://hogash-demos.com/kalypso_html/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Kallyas" class="img-responsive" src="/img/kallyas.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Kallyas</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Kallyas" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://demo.t2themes.com/html/fluidapp/light/" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Fluid App" class="img-responsive" src="/img/fluidapp.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Fluid App</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="Fluid App" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
					<li class="isotope-item temas">
						<div class="portfolio-item img-thumbnail">
							<a href="http://denoizzed.com/templates/photo/kingsize/multipage/index.html" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="King Size" class="img-responsive" src="/img/kingsize.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">King Size</span>
									<span class="thumb-info-type">Tema</span>
								</span>
								<span class="thumb-info-action">
									<span title="King Size" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>
 					<li class="isotope-item cases">
						<div class="portfolio-item img-thumbnail">
							<a href="http://consorcionet.com.br" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Consórcio Net" class="img-responsive" src="/img/consorcionet.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Consórcio Net</span>
									<span class="thumb-info-type">Case</span>
								</span>
								<span class="thumb-info-action">
									<span title="Consórcio Net" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>                   
                    <li class="isotope-item cases">
						<div class="portfolio-item img-thumbnail">
							<a href="http://jornaldoconsorcio.com.br" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Jornal do Consórcio" class="img-responsive" src="/img/jornal.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Jornal do Consórcio</span>
									<span class="thumb-info-type">Case</span>
								</span>
								<span class="thumb-info-action">
									<span title="Jornal do Consórcio" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li>


                    <li class="isotope-item cases">
						<div class="portfolio-item img-thumbnail">
							<a href="http://consorciodecarro.com.br" rel="nofollow" target="_blank" class="thumb-info secundary">
								<img alt="Consórcio Chevrolet" class="img-responsive" src="/img/chevrolet.jpg">
								<span class="thumb-info-title">
									<span class="thumb-info-inner">Consórcio Chevrolet</span>
									<span class="thumb-info-type">Case</span>
								</span>
								<span class="thumb-info-action">
									<span title="Consórcio Chevrolet" class="thumb-info-action-icon"><i class="fa fa-link"></i></span>
								</span>
							</a>
						</div>
					</li> 		
                </ul>


			<section class="call-to-action featured footer no-arrow">
				<div class="container">
					<div class="row">
						<div class="center">
							<h3>Gostou de algum case ou tema? Quer o seu site parecido com algum deles? <br />
Ligue para <strong>(**)*****-***** ou Skype ********* </strong> e peça um orçamento. <a href="/athos/contato" target="_blank" class="btn btn-lg btn-primary" data-appear-animation="bounceIn">Entre em Contato!</a> <span class="arrow hlb hidden-xs hidden-sm hidden-md" data-appear-animation="rotateInUpLeft" style="top: 15px;"></span></h3>
						</div>
					</div>
				</div>
			</section>

