<div role="main" class="main">

				<section class="page-top">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<ul class="breadcrumb">
									<li><a href="/">Home</a></li>
									<li class="active">Serviços</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h1>Serviços</h1>
							</div>
						</div>
					</div>
				</section>

				<div class="container">

					<h2>Nossos <strong>Serviços</strong></h2>

					<div class="row">
						<div class="col-md-10">
							<p class="lead">
								Nós da Athos Publicidade oferecemos serviços em desenvolvimento web e montagem e manutenção de redes com qualidade, integridade e funcionamento excelentes.
							</p>
						</div>
						<div class="col-md-2">
							<a href="/athos/contato" class="btn btn-lg btn-primary push-top pull-right">Entre em Contato!</a>
						</div>
					</div>

					<hr>

					<div class="row featured-boxes">
						<div class="col-md-3 col-sm-6">
							<div class="featured-box featured-box-secundary">
								<div class="box-content color-box-red-bd min_adjust">
									<i class="icon-featured fa fa-html5 color-box-red-bg"></i>
									<h4 class="color-box-red-txt">Desenvolvimento Web</h4>
									<p>Desenvolvemos sites e sistemas responsivos utilizando as tecnologias HTML5, CSS3 e JS.<a href="/athos/servicos/sobre/desenvolvimento-web" class="learn-more">Saiba mais... </a></p>
								</div>
							</div>
                            
                            
						</div>
						
						<div class="col-md-3 col-sm-6">
							<div class="featured-box featured-box-tertiary">
								<div class="box-content min_adjust">
									<i class="icon-featured fa fa-linux"></i>
									<h4>Serviços em Redes</h4>
									<p>Oferecemos uma ampla variedade de serviços em desenvolvimento e manutenção de redes.<a href="/athos/contato" class="learn-more">Saiba mais...</a></p>
								</div>
							</div>
						</div>
                        
                        
                        
						<div class="col-md-3 col-sm-6">
							<div class="featured-box featured-box-quartenary">
								<div class="box-content min_adjust">
									<i class="icon-featured fa fa-server"></i>
									<h4>Hospedagem</h4>
									<p>Temos planos para hospedagem do seu site ou sistema com baixo custo e alta qualidade. <a href="/athos/contato" class="learn-more">Saiba mais...</a></p>
								</div>
							</div>
						</div>
                        
                        <div class="col-md-3 col-sm-6">
							<div class="featured-box featured-box-tertiary">
								<div class="box-content min_adjust color-box-orange-bd">
									<i class="icon-featured fa fa-search color-box-orange-bg"></i>
									<h4 class="color-box-orange-txt">Consultoria SEO</h4>
									<p>Otimizamos seu website para aumentar o seu número de visitantes através dos mecanismos de busca.<a href="/athos/contato" class="learn-more">Saiba mais...</a></p>
								</div>
							</div>
						</div>
                        
					</div>
					
                    <div class="row featured-boxes">
                       <div class="col-md-3 col-sm-6">
							<div class="featured-box featured-box-tertiary tp_zero">
								<div class="box-content min_adjust color-box-darkblue-bd">
									<i class="icon-featured fa fa-facebook color-box-darkblue-bg"></i>
									<h4 class="color-box-darkblue-txt">Facebook Marketing</h4>
									<p>Administramos sua página e campanha para conseguir mais curtidas e seguidores.<a href="/athos/contato" class="learn-more">Saiba mais...</a></p>
								</div>
							</div>
						</div>
                        
                        <div class="col-md-3 col-sm-6">
							<div class="featured-box featured-box-tertiary tp_zero">
								<div class="box-content min_adjust color-box-green-bd">
									<i class="icon-featured fa fa-google color-box-green-bg"></i>
									<h4 class="color-box-green-txt">Adwords</h4>
									<p>Criamos e melhoramos sua campanha no AdWords para conseguir mais cliques e resultados.<a href="/athos/contato" class="learn-more">Saiba mais...</a></p>
								</div>
							</div>
						</div>
                        
                        <div class="col-md-3 col-sm-6">
							<div class="featured-box featured-box-tertiary tp_zero">
								<div class="box-content min_adjust color-box-pink-bd">
									<i class="icon-featured fa fa-phone color-box-pink-bg"></i>
									<h4 class="color-box-pink-txt">PABX IP</h4>
									<p>Soluções de Pabx IP com recursos que proporcionam uma super economia e facilidade no gerenciamento de sua telefonia.<a href="/athos/contato" class="learn-more">Saiba mais...</a></p>
								</div>
							</div>
						</div>
                        
                        <div class="col-md-3 col-sm-6">
							<div class="featured-box featured-box-primary tp_zero">
								<div class="box-content color-box-blue-bd min_adjust">
									<i class="icon-featured fa fa-user color-box-blue-bg"></i>
									<h4 class="color-box-blue-txt">Atendimento</h4>
									<p>
                                       Excelente atendimento a você que utiliza ou ainda não utilizou de nossos serviços, nós pensamos em você!
                                       <a href="/athos/contato" class="learn-more">Saiba mais...</a>
                                    </p>
								</div>
							</div>
                            
						</div>
                    </div>
                    
					<div class="row">
						<div class="col-md-8">
							<h2>Nós <strong>Oferecemos</strong></h2>
							<div class="row">
								<div class="col-sm-6">
									<div class="feature-box">
										<div class="feature-box-icon">
                                        	<i class="fa fa-file"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">HTML5 / CSS3 / JS</h4>
											<p class="tall">Desenvolvimento de websites e sistemas com as últimas tecnologias.</p>
										</div>
									</div>
									<div class="feature-box">
										<div class="feature-box-icon">
											<i class="fa fa-bars"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">Responsividade</h4>
											<p class="tall">Websites responsivos para alavancar ainda mais os seus resultados no mundo mobile.</p>
										</div>
									</div>
                                    <div class="feature-box">
										<div class="feature-box-icon">
											<i class="fa fa-desktop"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">Serviços em Redes</h4>
											<p class="tall">Montamos sua rede e prestamos manutenção</p>
										</div>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="feature-box">
										<div class="feature-box-icon">
										<i class="fa fa-server"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">Hospedagem de Websites</h4>
											<p class="tall">Oferecemos hospedagem de qualidade e com valores que cabem no seu bolso.</p>
										</div>
									</div>
									<div class="feature-box">
										<div class="feature-box-icon">
											<i class="fa fa-user-plus"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">Suporte ao Cliente</h4>
											<p class="tall">Contamos com um sistema de atendimento excelente para não te deixar na mão.</p>
										</div>
									</div>
									<div class="feature-box">
										<div class="feature-box-icon">
											<i class="fa fa-terminal"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">VPN</h4>
											<p class="tall">Implantação de VPN</p>
										</div>
									</div>
									
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<h2>e mais...</h2>
				
							<div class="panel-group" id="accordion">
								
								<div class="panel panel-default">
									<div class="panel-heading">
										<h4 class="panel-title">
											<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
												<i class="fa fa-comment"></i>
												Formulário de Contato
											</a>
										</h4>
									</div>
									<div id="collapseTwo" class="accordion-body collapse in">
										<div class="panel-body">
											<a href="/athos/contato">Clique aqui</a> e entre em contato com a gente, nos conte
                                            quais são seus problemas para que possamos resolvê-los.
										</div>
									</div>
								</div>
								<div class="panel panel-default">
									<div class="panel-heading">
										<h4 class="panel-title">
											<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
												<i class="fa fa-laptop"></i>
												Cases e Temas
											</a>
										</h4>
									</div>
									<div id="collapseThree" class="accordion-body collapse">
										<div class="panel-body">
											Confira nossos cases e temas prediletos <a href="/athos/cases-e-temas">clicando aqui.</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					<hr class="tall" />

					<div class="row">
						<div class="col-sm-7">
							<h2>Venha <strong>Conhecer</strong></h2>
							<p class="lead">
								Se você se interessou por algum dos nossos serviços e deseja saber mais ou marcar uma reunião com a gente. Ligue: (--) ****** - ******
                                ou Skype **********
							</p>
							<p class="tall">
								Ficaremos felizes em atendê-lo(a)!.
							</p>
						</div>
						<div class="col-sm-4 col-sm-offset-1 push-top">
							<img class="img-responsive" src="/img/device.png">
						</div>
					</div>

				</div>

			</div>