<div role="main" class="main">

				<section class="page-top">
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<ul class="breadcrumb">
									<li><a href="#">Home</a></li>
									<li class="active">Sobre</li>
								</ul>
							</div>
						</div>
						<div class="row">
							<div class="col-md-12">
								<h1>Sobre</h1>
							</div>
						</div>
					</div>
				</section>

				<div class="container">

					<div class="row center">
						<div class="col-md-12">
							<h2 class="short word-rotator-title">
                               <?php
							   			//echo utf8_encode($array[0]['descricao']);	

							    echo $servico;?>
							</h2>
							<p class="featured lead">
								<?php echo $descricao; ?>
							</p>
						</div>
					</div>

					<hr class="tall" />
				</div>

				<div class="container">

					<div class="row">
						<div class="col-md-12">
							<div class="row">
								<div class="col-md-4">
									<div class="feature-box secundary">
										<div class="feature-box-icon">
											<i class="fa fa-html5"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">DESENVOLVIMENTO WEB</h4>
											<p class="tall">Desenvolvemos sites e sistemas responsivos utilizando as tecnologias HTML5, CSS3 e JS.</p>
										</div>
									</div>
									
                                    <div class="feature-box secundary">
										<div class="feature-box-icon">
											<i class="fa fa-linux"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">SERVIÇOS EM REDES

</h4>
											<p class="tall">Oferecemos uma ampla variedade de serviços em desenvolvimento e manutenção de redes.</p>
										</div>
									</div>
                                    
                                    <div class="feature-box secundary">
										<div class="feature-box-icon">
											<i class="fa fa-phone"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">PABX IP</h4>
											<p class="tall">Soluções de Pabx IP com recursos que proporcionam uma super economia e facilidade no gerenciamento de sua telefonia.</p>
										</div>
									</div>
                                    
								</div>
								<div class="col-md-4">
									<div class="feature-box secundary">
										<div class="feature-box-icon">
											<i class="fa fa-server"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">HOSPEDAGEM</h4>
											<p class="tall">Temos planos para hospedagem do seu site ou sistema com baixo custo e alta qualidade.
</p>
										</div>
									</div>
									<div class="feature-box secundary">
										<div class="feature-box-icon">
											<i class="fa fa-search"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">CONSULTORIA SEO</h4>
											<p class="tall">Otimizamos seu website para aumentar o seu número de visitantes através dos mecanismos de busca.
</p>
										</div>
									</div>
                                    
                                    <div class="feature-box secundary">
										<div class="feature-box-icon">
											<i class="fa fa-user"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">ATENDIMENTO</h4>
											<p class="tall">Excelente atendimento a você que utiliza ou ainda não utilizou de nossos serviços, nós pensamos em você!
</p>
										</div>
									</div>
                                    
								</div>
								<div class="col-md-4">
									<div class="feature-box secundary">
										<div class="feature-box-icon">
											<i class="fa fa-facebook"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">FACEBOOK MARKETING</h4>
											<p class="tall">Administramos sua página e campanha para conseguir mais curtidas e seguidores.
</p>
										</div>
									</div>
									<div class="feature-box secundary">
										<div class="feature-box-icon">
											<i class="fa fa-google"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">ADWORDS</h4>
											<p class="tall">Criamos e melhoramos sua campanha no AdWords para conseguir mais cliques e resultados.
</p>
										</div>
									</div>
								</div>
							</div>
                            
                            
                            
                            
                            
						</div>
					</div>

				</div>

				

    <section class="video" data-video-path="/videos/light" data-plugin-video-background data-plugin-options='{"posterType": "jpg", "position": "50% 50%"}' style="padding-top: 100px;padding-bottom: 100px;">
					<div class="container">
						<div class="row center">
							<div class="col-md-12">

                                                            <span style="font-size:25px; color:#333; font-weight: bold; ">Nós oferecemos serviços para que você possa <span class="alternative-font" style="font-size:30px; font-weight: bold;">realmente</span> atingir os seus objetivos,
                                                                    entre em contato conosco e nos dê a oportunidade de ajudá-lo.</span>
                                                            <br><br>
                                                            <span style="font-size:20px; color:#666;">Ligue: (**) ****-**** ou Skype: **********</span>

							</div>
						</div> 

					</div>
				</section>

				

				

				<section class="call-to-action featured footer">
					<div class="container">
						<div class="row">
							<div class="center">
								<h3>Porto is <strong>everything</strong> you need to create an <strong>awesome</strong> website! <a href="http://themeforest.net/item/porto-responsive-html5-template/4106987" target="_blank" class="btn btn-lg btn-primary" data-appear-animation="bounceIn">Buy Now!</a> <span class="arrow hlb hidden-xs hidden-sm hidden-md" data-appear-animation="rotateInUpLeft" style="top: -22px;"></span></h3>
							</div>
						</div>
					</div>
				</section>

			</div>
