
<div class="slider-container">
					<div class="slider" id="revolutionSlider" data-plugin-revolution-slider data-plugin-options='{"startheight": 500}'>
						<ul>
							<li data-transition="fade" data-slotamount="13" data-masterspeed="300" >
				
								<img src="/img/slides/slide-bg.jpg" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
				
								<div class="tp-caption sft stb visible-lg"
									 data-x="177"
									 data-y="180"
									 data-speed="300"
									 data-start="1000"
									 data-easing="easeOutExpo"><img src="/img/slides/slide-title-border.png" alt=""></div>
				
								<div class="tp-caption top-label lfl stl"
									 data-x="227"
									 data-y="180"
									 data-speed="300"
									 data-start="500"
									 data-easing="easeOutExpo">PRECISANDO DE UM</div>
				
								<div class="tp-caption sft stb visible-lg"
									 data-x="477"
									 data-y="180"
									 data-speed="300"
									 data-start="1000"
									 data-easing="easeOutExpo"><img src="/img/slides/slide-title-border.png" alt=""></div>
				
								<div class="tp-caption main-label sft stb"
									 data-x="190"
									 data-y="210"
									 data-speed="300"
									 data-start="1500"
									 data-easing="easeOutExpo">WEB SITE?</div>
				
								<div class="tp-caption bottom-label sft stb"
									 data-x="140"
									 data-y="280"
									 data-speed="500"
									 data-start="2000"
									 data-easing="easeOutExpo">Ligue (--) **** - **** ou Skype **********</div>
				
								<div class="tp-caption randomrotate"
									 data-x="905"
									 data-y="248"
									 data-speed="500"
									 data-start="2500"
									 data-easing="easeOutBack"><img src="/img/slides/slide-concept-2-1.png" alt=""></div>
				
								<div class="tp-caption sfb"
									 data-x="955"
									 data-y="200"
									 data-speed="400"
									 data-start="3000"
									 data-easing="easeOutBack"><img src="/img/slides/slide-concept-2-2.png" alt=""></div>
				
								<div class="tp-caption sfb"
									 data-x="925"
									 data-y="170"
									 data-speed="700"
									 data-start="3150"
									 data-easing="easeOutBack"><img src="/img/slides/slide-concept-2-3.png" alt=""></div>
				
								<div class="tp-caption sfb"
									 data-x="875"
									 data-y="130"
									 data-speed="1000"
									 data-start="3250"
									 data-easing="easeOutBack"><img src="/img/slides/slide-concept-2-4.png" alt=""></div>
				
								<div class="tp-caption sfb"
									 data-x="605"
									 data-y="80"
									 data-speed="600"
									 data-start="3450"
									 data-easing="easeOutExpo"><img src="/img/slides/slide-concept-2-5.png" alt=""></div>
				
								<div class="tp-caption blackboard-text lfb "
									 data-x="635"
									 data-y="300"
									 data-speed="500"
									 data-start="3450"
									 data-easing="easeOutExpo" style="font-size: 37px;">Pensamos</div>
				
								<div class="tp-caption blackboard-text lfb "
									 data-x="660"
									 data-y="350"
									 data-speed="500"
									 data-start="3650"
									 data-easing="easeOutExpo" style="font-size: 47px;">Fora</div>
				
								<div class="tp-caption blackboard-text lfb "
									 data-x="685"
									 data-y="400"
									 data-speed="500"
									 data-start="3850"
									 data-easing="easeOutExpo" style="font-size: 32px;">da caixa :)</div>
							</li>
							<li data-transition="fade" data-slotamount="5" data-masterspeed="1000" >
				
								<img src="/img/slides/slide-bg.jpg" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
				
									<div class="tp-caption sft stb"
										 data-x="155"
										 data-y="100"
										 data-speed="600"
										 data-start="100"
										 data-easing="easeOutExpo"><img src="/img/slides/slide-concept.png" alt=""></div>
				
									<div class="tp-caption blackboard-text sft stb"
										 data-x="260"
										 data-y="180"
										 data-speed="900"
										 data-start="1000"
										 data-easing="easeOutExpo" style="font-size: 30px;">Prestamos Serviços</div>
				
									<div class="tp-caption blackboard-text sft stb"
										 data-x="285"
										 data-y="220"
										 data-speed="900"
										 data-start="1200"
										 data-easing="easeOutExpo" style="font-size: 40px;">em Redes!</div>
				
									<div class="tp-caption main-label sft stb"
										 data-x="685"
										 data-y="190"
										 data-speed="300"
										 data-start="900"
										 data-easing="easeOutExpo">MONTAMOS</div>
									
                                    <div class="tp-caption main-label sft stb"
										 data-x="685"
										 data-y="255"
										 data-speed="300"
										 data-start="900"
										 data-easing="easeOutExpo">SUA REDE!!!</div>
				
									<div class="tp-caption bottom-label sft stb"
										 data-x="685"
										 data-y="340"
										 data-speed="500"
										 data-start="2000"
										 data-easing="easeOutExpo">Ligue (--) **** - **** ou Skype **********</div>
				
							</li>
                            
                            <li data-transition="fade" data-slotamount="5" data-masterspeed="1000" >
				
								<img src="/img/slides/slide-bg.jpg" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
				
								
				
									<div class="tp-caption blackboard-text sft stb"
										 data-x="200"
										 data-y="100"
										 data-speed="900"
										 data-start="1000"
										 data-easing="easeOutExpo" style="font-size: 30px;">TAMBÉM TEMOS</div>
				
									<div class="tp-caption blackboard-text sft stb"
										 data-x="235"
										 data-y="150"
										 data-speed="900"
										 data-start="1200"
										 data-easing="easeOutExpo" style="font-size: 40px;">SERVIÇO DE HOSPEDAGEM! ;)</div>
				
									<div class="tp-caption main-label sft stb"
										 data-x="340"
										 data-y="220"
										 data-speed="300"
										 data-start="900"
										 data-easing="easeOutExpo">Hospede seu site</div>
									
                                    <div class="tp-caption main-label sft stb"
										 data-x="340"
										 data-y="285"
										 data-speed="300"
										 data-start="900"
										 data-easing="easeOutExpo">com a gente!!!</div>
				
									<div class="tp-caption bottom-label sft stb"
										 data-x="400"
										 data-y="370"
										 data-speed="500"
										 data-start="2000"
										 data-easing="easeOutExpo">Ligue (--) **** - **** ou Skype **********</div>
				
							</li>
<li data-transition="fade" data-slotamount="5" data-masterspeed="1000" >
				
								<img src="/img/slides/slide-bg.jpg" data-bgfit="cover" data-bgposition="left top" data-bgrepeat="no-repeat">
				
								
				
									<div class="tp-caption blackboard-text sft stb"
										 data-x="70"
										 data-y="190"
										 data-speed="900"
										 data-start="900"
										 data-easing="easeOutExpo" style="font-size: 26px;">Quer ter mais acessos no seu site? </div>
				
									
				
                					
                                    
                                    
                
									<div class="tp-caption blackboard-text sft stb"
										 data-x="40"
										 data-y="240"
										 data-speed="300"
										 data-start="1500"
										 data-easing="easeOutExpo" style="font-size: 50px;">Ligue (--) **** - ****</div>
									
                                    <div class="tp-caption blackboard-text sft stb"
										 data-x="65"
										 data-y="300"
										 data-speed="300"
										 data-start="1600"
										 data-easing="easeOutExpo">ou Skype **********</div>
                                    
                                    <div class="tp-caption main-label sft stb"
										 data-x="570"
										 data-y="130"
										 data-speed="300"
										 data-start="900"
										 data-easing="easeOutExpo">CONSULTORIA SEO,</div>
									
                                    <div class="tp-caption main-label sft stb"
										 data-x="680"
										 data-y="200"
										 data-speed="300"
										 data-start="1200"
										 data-easing="easeOutExpo">ADWORDS E</div>
                                    
                                    <div class="tp-caption main-label sft stb"
										 data-x="700"
										 data-y="270"
										 data-speed="300"
										 data-start="1500"
										 data-easing="easeOutExpo">FACEBOOK</div>
                                    
                                    <div class="tp-caption main-label sft stb"
										 data-x="670"
										 data-y="340"
										 data-speed="300"
										 data-start="1500"
										 data-easing="easeOutExpo">MARKETING!</div>
                                    
                                    
                                     <div class="tp-caption bottom-label sft stb"
										 data-x="150"
										 data-y="360"
										 data-speed="300"
										 data-start="1600"
										 data-easing="easeOutExpo">NÓS PODEMOS TE AJUDAR!</div>
									
				
							</li>                            
						</ul>
					</div>
				</div>
				<div class="home-intro" id="home-intro">
					<div class="container">
				
						<div class="row">
							<div class="col-md-8">
								<p style="font-size:1.2em;">
									Desenvolvimento de Sistemas, serviços em redes, hospedagem e <em>Websites Responsivos</em>
									<span>Contato: (--) ****-**** ou Skype *********.</span>
								</p>
							</div>
							<div class="col-md-4">
								<div class="get-started">
									<a href="/athos/contato" class="btn btn-lg btn-primary">Contate-nos!</a>
									<div class="learn-more">ou <a href="/athos/cases-e-temas">confira nossos cases!</a></div>
								</div>
							</div>
						</div>
				
					</div>
				</div>
				
				<div class="container">
				
					<div class="row center">
						<div class="col-md-12">
							<h1 class="short word-rotator-title">
								Websites e Sistemas
								<strong class="inverted">
									<span class="word-rotate" data-plugin-options='{"delay": 2000, "animDelay": 300}'>
										<span class="word-rotate-items">
											<span>incrivelmente</span>
											<span>especialmente</span>
											<span>extremamente</span>
										</span>
									</span>
								</strong>
								belos e cheios de responsividade.
							</h1>
							<p class="featured lead">
								Nós da Athos contamos com um excelente e comprovado processo de desenvolvimento e prestação de serviços
                                desde a elaboração até o momento da entrega! 
							</p>
						</div>
					</div>
				
				</div>
				
				<div class="home-concept">
					<div class="container">
				
						<div class="row center">
							<span class="sun"></span>
							<span class="cloud"></span>
							<div class="col-md-2 col-md-offset-1">
								<div class="process-image" data-appear-animation="bounceIn">
											<img class="img-responsive" src="/img/img2.jpg" />
									<strong>Estratégia</strong>
								</div>
							</div>
							<div class="col-md-2">
								<div class="process-image" data-appear-animation="bounceIn" data-appear-animation-delay="200">
											<a href="portfolio-single-project.html"><img class="img-responsive" src="/img/img2.jpg" /></a>
									<strong>Planejamento</strong>
								</div>
							</div>
							<div class="col-md-2">
								<div class="process-image" data-appear-animation="bounceIn" data-appear-animation-delay="400">
											<a href="portfolio-single-project.html"><img class="img-responsive" src="/img/img1.jpg" /></a>
									<strong>Construção</strong>
								</div>
							</div>
							<div class="col-md-4 col-md-offset-1">
								<div class="project-image">
									<div id="fcSlideshow" class="fc-slideshow">
										<ul class="fc-slides">
											<li><a href="portfolio-single-project.html"><img class="img-responsive" src="/img/img1.jpg" /></a></li>
											<li><a href="portfolio-single-project.html"><img class="img-responsive" src="/img/img2.jpg" /></a></li>
										</ul>
									</div>
									<strong class="our-work">Nosso trabalho</strong>
								</div>
							</div>
						</div>
				
					</div>
				</div>
				
				<div class="container">
				
					<div class="row">
						<hr class="tall" />
					</div>
				
				</div>
				
				<div class="container">
				
					<div class="row">
						<div class="col-md-8">
							<h2>Nós <strong>Oferecemos</strong></h2>
							<div class="row">
								<div class="col-sm-6">
									<div class="feature-box">
										<div class="feature-box-icon">
                                        	<i class="fa fa-file"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">HTML5 / CSS3 / JS</h4>
											<p class="tall">Desenvolvimento de websites e sistemas com as últimas tecnologias.</p>
										</div>
									</div>
									<div class="feature-box">
										<div class="feature-box-icon">
											<i class="fa fa-bars"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">Responsividade</h4>
											<p class="tall">Websites responsivos para alavancar ainda mais os seus resultados no mundo mobile.</p>
										</div>
									</div>
                                    <div class="feature-box">
										<div class="feature-box-icon">
											<i class="fa fa-desktop"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">Serviços em Redes</h4>
											<p class="tall">Montamos sua rede e prestamos manutenção</p>
										</div>
									</div>
								</div>
								<div class="col-sm-6">
									<div class="feature-box">
										<div class="feature-box-icon">
										<i class="fa fa-server"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">Hospedagem de Websites</h4>
											<p class="tall">Oferecemos hospedagem de qualidade e com valores que cabem no seu bolso.</p>
										</div>
									</div>
									<div class="feature-box">
										<div class="feature-box-icon">
											<i class="fa fa-user-plus"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">Suporte ao Cliente</h4>
											<p class="tall">Contamos com um sistema de atendimento excelente para não te deixar na mão.</p>
										</div>
									</div>
									<div class="feature-box">
										<div class="feature-box-icon">
											<i class="fa fa-terminal"></i>
										</div>
										<div class="feature-box-info">
											<h4 class="shorter">VPN</h4>
											<p class="tall">Implantação de VPN</p>
										</div>
									</div>
									
								</div>
							</div>
						</div>
						<div class="col-md-4">
							<h2>e mais...</h2>
				
							<div class="panel-group" id="accordion">
								
								<div class="panel panel-default">
									<div class="panel-heading">
										<h4 class="panel-title">
											<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
												<i class="fa fa-comment"></i>
												Formulário de Contato
											</a>
										</h4>
									</div>
									<div id="collapseTwo" class="accordion-body collapse in">
										<div class="panel-body">
											<a href="/athos/contato">Clique aqui</a> e entre em contato com a gente, nos conte
                                            quais são seus problemas para que possamos resolvê-los.
										</div>
									</div>
								</div>
								<div class="panel panel-default">
									<div class="panel-heading">
										<h4 class="panel-title">
											<a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
												<i class="fa fa-laptop"></i>
												Cases e Temas
											</a>
										</h4>
									</div>
									<div id="collapseThree" class="accordion-body collapse">
										<div class="panel-body">
											Confira nossos cases e temas prediletos <a href="/athos/cases-e-temas">clicando aqui.</a>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				
					<hr class="tall" />
				
					<div class="row center">
						<div class="col-md-12">
							<h2 class="short word-rotator-title">
								Entre em contato com a gente, nós ficaremos
								<strong>
									<span class="word-rotate" data-plugin-options='{"delay": 3500, "animDelay": 400}'>
										<span class="word-rotate-items">
											<span>felizes</span>
											<span>satisfeitos</span>
                                            <span>alegres</span>
                                            
										</span>
									</span>
								</strong>
								em te ajudar!
							</h2>
						</div>
					</div>
					
				
				</div>
				
				