<?php
include("includes/dominio.php");
?>
<!DOCTYPE html>
<html>
	<head>

		<!-- Basic -->
		<meta charset="utf-8">
		<title>Athos - Desenvolvimento e Publicidade</title>
		<meta name="description" content="A Athos é uma empresa de publicidade que atua desenvolvendo projetos criativos e efeicientes buscando sempre a satisfação do cliente">
		<meta name="keywords" content="desenvolvimento web, webdesigner, serviços em redes, hospedagem, instalação de vpn, web, athos, publicidade, desenvolvimento e publicidade"> 
		<meta name="author" content="Athos Desenvolvimento e publicidade"> 
		
        
        
		<!-- Mobile Metas -->
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
        <link rel="apple-touch-icon" sizes="57x57" href="/img/apple-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/img/apple-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/img/apple-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/img/apple-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/img/apple-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/img/apple-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/img/apple-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/img/apple-icon-152x152.png">
		<link rel="apple-touch-icon" sizes="180x180" href="/img/apple-icon-180x180.png">
		<link rel="icon" type="image/png" sizes="192x192"  href="/img/android-icon-192x192.png">
		<link rel="icon" type="image/png" sizes="32x32" href="/img/favicon-32x32.png">
		<link rel="icon" type="image/png" sizes="96x96" href="/img/favicon-96x96.png">
		<link rel="icon" type="image/png" sizes="16x16" href="/img/favicon-16x16.png">
		<link rel="manifest" href="/img/manifest.json">
		<meta name="msapplication-TileColor" content="#ffffff">
		<meta name="msapplication-TileImage" content="/img/ms-icon-144x144.png">
		<meta name="theme-color" content="#ffffff">
        
		<!-- Web Fonts  -->
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light" rel="stylesheet" type="text/css">
		
        
		<!-- Vendor CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/vendor/bootstrap/bootstrap.css">
		<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
		
        
        <link rel="stylesheet" href="<?php echo $dominio;?>/vendor/owlcarousel/owl.carousel.min.css" media="screen">
		<link rel="stylesheet" href="<?php echo $dominio;?>/vendor/owlcarousel/owl.theme.default.min.css" media="screen">
		<link rel="stylesheet" href="<?php echo $dominio;?>/vendor/magnific-popup/magnific-popup.css" media="screen">

		<!-- Theme CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme.css">
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme-elements.css">
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme-blog.css">
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme-shop.css">
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/theme-animate.css">
		
		<!-- Current Page CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/vendor/rs-plugin/css/settings.css" media="screen">
		<link rel="stylesheet" href="<?php echo $dominio;?>/vendor/circle-flip-slideshow/css/component.css" media="screen">

		<!-- Skin CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/skins/default.css">

		<!-- Theme Custom CSS -->
		<link rel="stylesheet" href="<?php echo $dominio;?>/css/custom.css">

		<!-- Head Libs -->
		<script src="<?php echo $dominio;?>/vendor/modernizr/modernizr.js"></script>

		<!--[if IE]>
			<link rel="stylesheet" href="<?php echo $dominio;?>/css/ie.css">
		<![endif]-->

		<!--[if lte IE 8]>
			<script src="<?php echo $dominio;?>/vendor/respond/respond.js"></script>
			<script src="<?php echo $dominio;?>/vendor/excanvas/excanvas.js"></script>
		<![endif]-->

	</head>
	<body>
		<div class="body">
			
			<?php include('includes/head.php');?>

			<div role="main" class="main">
            <?php echo $this->content; ?>
           </div>
 
			<?php include('includes/footer.php');?>
            
		</div>

		<!-- Vendor -->
		<script src="<?php echo $dominio;?>/vendor/jquery/jquery.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.appear/jquery.appear.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.easing/jquery.easing.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery-cookie/jquery-cookie.js"></script>
		<script src="<?php echo $dominio;?>/vendor/bootstrap/bootstrap.js"></script>
		<script src="<?php echo $dominio;?>/vendor/common/common.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.validation/jquery.validation.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.stellar/jquery.stellar.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.easy-pie-chart/jquery.easy-pie-chart.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jquery.gmap/jquery.gmap.js"></script>
		<script src="<?php echo $dominio;?>/vendor/isotope/jquery.isotope.js"></script>
		<script src="<?php echo $dominio;?>/vendor/owlcarousel/owl.carousel.js"></script>
		<script src="<?php echo $dominio;?>/vendor/jflickrfeed/jflickrfeed.js"></script>
		<script src="<?php echo $dominio;?>/vendor/magnific-popup/jquery.magnific-popup.js"></script>
		<script src="<?php echo $dominio;?>/vendor/vide/vide.js"></script>
		
		<!-- Theme Base, Components and Settings -->
		<script src="<?php echo $dominio;?>/js/theme.js"></script>
		
		<!-- Specific Page Vendor and Views -->
		<script src="<?php echo $dominio;?>/vendor/rs-plugin/js/jquery.themepunch.tools.min.js"></script>
		<script src="<?php echo $dominio;?>/vendor/rs-plugin/js/jquery.themepunch.revolution.min.js"></script>
		<script src="<?php echo $dominio;?>/vendor/circle-flip-slideshow/js/jquery.flipshow.js"></script>
		<script src="<?php echo $dominio;?>/js/views/view.home.js"></script>
		
		<!-- Theme Custom -->
		<script src="<?php echo $dominio;?>/js/custom.js"></script>
		
		<!-- Theme Initialization Files -->
		<script src="<?php echo $dominio;?>/js/theme.init.js"></script>
		
		<script src="<?php echo $dominio;?>/js/treatments.js"></script>
		 
            
        
		<?php include('includes/analytics.php');?>
		

	</body>
</html>